# Generated by Django 4.2.11 on 2025-11-17 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0004_remove_filme_diretor_filme_diretores'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filme',
            options={'verbose_name': 'Filmes', 'verbose_name_plural': 'filmes'},
        ),
        migrations.RemoveField(
            model_name='filme',
            name='diretores',
        ),
        migrations.RemoveField(
            model_name='filme',
            name='generos',
        ),
    ]
