# Generated by Django 5.2.8 on 2025-11-27 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0005_alter_filme_options_remove_filme_diretores_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filme',
            options={'ordering': ['id'], 'verbose_name': 'Filmes', 'verbose_name_plural': 'filmes'},
        ),
    ]
