# Generated by Django 5.2.8 on 2025-12-01 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diretores', '0001_initial'),
        ('filmes', '0006_alter_filme_options'),
        ('genero', '0002_alter_genero_options_alter_genero_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='filme',
            name='diretores',
            field=models.ManyToManyField(blank=True, to='diretores.diretor'),
        ),
        migrations.AddField(
            model_name='filme',
            name='generos',
            field=models.ManyToManyField(related_name='filmes', to='genero.genero'),
        ),
    ]
